let express=require("express")
let mongoose=require("mongoose")
const router = require("./routers/userRouts")
const bodyParser=require("body-parser")
const app= express()
app.use(express.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use("/api",router)
mongoose.connect("mongodb://127.0.0.1:27017/task2").then(()=>{console.log("DataBase connected")}).catch(("NOt connectd"))
app.listen(5000,()=>{console.log("server is connected....")})